version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.prod
    container_name: api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - BASE_URL=http://apalabajar.shop  # Removed space around '='
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: dockerfile.prod
    container_name: front-end
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL=http://api:4000/api
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
